# -*- coding: utf-8 -*-
"""Data logging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KTkm2AJiLNfjmNOyYphnP1SU7sF45Ykz
"""

import xlsxwriter

# Workbook() takes one, non-optional, argument
# which is the filename that we want to create.
wb = input('enter the filename')
workbook = xlsxwriter.Workbook(f'{wb}.xlsx')
# The workbook object is then used to add new
# worksheet via the add_worksheet() method.
worksheet = workbook.add_worksheet()
x=1

# Use the worksheet object to write
# data via the write() method
while(1):
  worksheet.write('A1', 'Name')
  worksheet.write( 'B1', 'Phone No')
  worksheet.write('C1', 'Place')
  worksheet.write('D1', 'Body Temp')
  worksheet.write(x,0,input('enter the name'))
  worksheet.write(x,1,input('enter the phone no'))
  worksheet.write(x,2,input('Place of origin'))
  worksheet.write(x,3,float(input('Body Temp')))
  x=x+1 
  e = input('c for continue e for exit')
  if e == 'e':
    break 
# Finally, close the Excel file
# via the close() method.
workbook.close()

pip install xlsxwriter

